
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
media_player:
  - platform: vlc
    name: speaker
    arguments: '--alsa-audio-device=hw:0,0'
shell_command:
        doorbell: aplay /config/www/audio/door.wav
